#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Sep 07 08:43:09 CST 2026
maven-metadata-handle.net.xml.error=
maven-metadata-central.xml.lastUpdated=1788741789605
maven-metadata-handle.net.xml.lastUpdated=1788741789605
maven-metadata-central-portal-snapshots.xml.lastUpdated=1788741789605
maven-metadata-central-portal-snapshots.xml.error=
