#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Sep 07 08:40:46 CST 2026
maven-metadata-handle.net.xml.error=
maven-metadata-central.xml.lastUpdated=1788741646888
maven-metadata-handle.net.xml.lastUpdated=1788741646889
maven-metadata-central-portal-snapshots.xml.lastUpdated=1788741646888
maven-metadata-central-portal-snapshots.xml.error=
